<?php
/*
SELECT 
    DATE_FORMAT(C.DATA_CONSULTA, '%Y/%m/%d') AS DATA_CONSULTA, 
    TRIM(LEADING '0' FROM DATE_FORMAT(C.HORA_CONSULTA, '%H:%i')) AS HORA_CONSULTA,
    P.NOME_PET, P.ID_PET, C.FK_CONSULTA_MEDICO AS ID_MEDICO,
    C.STATUS, C.RELATORIO_CONSULTA,
    U.NOMECOMPLETO_USUARIO AS MEDICO,
    A.NOMECOMPLETO_USUARIO AS ACOMPANHANTE
FROM CONSULTA C
INNER JOIN PET P ON P.ID_PET = C.FK_CONSULTA_PET
INNER JOIN USUARIO U ON U.ID_USUARIO = C.FK_CONSULTA_MEDICO
INNER JOIN USUARIO_PET UP ON P.ID_PET = UP.FK_PET
INNER JOIN USUARIO A ON UP.FK_USUARIO = A.ID_USUARIO
WHERE C.ID_CONSULTA = 26
AND (UP.FK_USUARIO = 11 OR C.FK_CONSULTA_MEDICO = 1);
*/
function runInformacoesConsulta($consulta){
    session_start();
    include("conexao.php");

    $comando = $pdo->prepare("SELECT DATE_FORMAT(C.DATA_CONSULTA, '%Y/%m/%d') AS DATA_CONSULTA, TRIM(LEADING '0' FROM DATE_FORMAT(C.HORA_CONSULTA, '%H:%i')) AS HORA_CONSULTA, P.NOME_PET, P.ID_PET, C.FK_CONSULTA_MEDICO AS ID_MEDICO, C.STATUS, C.RELATORIO_CONSULTA, U.NOMECOMPLETO_USUARIO AS MEDICO, A.NOMECOMPLETO_USUARIO AS ACOMPANHANTE FROM CONSULTA C INNER JOIN PET P ON P.ID_PET = C.FK_CONSULTA_PET INNER JOIN USUARIO U ON U.ID_USUARIO = C.FK_CONSULTA_MEDICO INNER JOIN USUARIO_PET UP ON P.ID_PET = UP.FK_PET INNER JOIN USUARIO A ON UP.FK_USUARIO = A.ID_USUARIO WHERE C.ID_CONSULTA = ? AND (UP.FK_USUARIO = ? OR C.FK_CONSULTA_MEDICO = ?);");

    $comando->execute([$consulta, $_SESSION['pk_usuario'], $_SESSION['pk_usuario']]);

    if ($comando->rowCount()==1)
    {
        $informacoes_consulta = $comando->fetch();
    }
    else {
        $informacoes_consulta = false;  
    }
    unset($comando);
    unset($pdo);
    return $informacoes_consulta;
}